i18n/es/cosmic_app_library.ftl
Translation to Spanish. I think everything is fine.
=> Spanish translation

i18n/pt-BR/cosmic_app_library.ftl
Initial translation into Brazilian Portuguese
=> feat: Translation pt-BR

i18n/cs/cosmic_app_library.ftl
=> i18n(cs):Add Czech language

Cargo.lock, Cargo.toml, LICENSE.md, i18n/cs/cosmic_app_library.ftl, i18n/en/cosmic_app_library.ftl, i18n/es/cosmic_app_library.ftl, i18n/fa/cosmic_app_library.ftl, i18n/fr/cosmic_app_library.ftl, i18n/ko/cosmic_app_library.ftl, i18n/pt-BR/cosmic_app_library.ftl, i18n/sr/cosmic_app_library.ftl, i18n/tr/cosmic_app_library.ftl, i18n/zh-CN/cosmic_app_library.ftl, src/app.rs, src/app_group.rs, src/main.rs, src/widgets/application.rs, src/widgets/group.rs, src/widgets/mod.rs
This adds DnD support, cosmic-config integration, editable groups, and popups for applications. Not all of this seems to be defined in the mockups, so I've made some guesses in the meantime that can be adjusted later.
=> Improvements jammy

Cargo.lock, Cargo.toml, src/app.rs, src/app_group.rs, src/widgets/application.rs, src/widgets/group.rs
=> fix: filter all by search on home only when search isn't empty

Cargo.lock, data/com.system76.CosmicAppLibrary.desktop, src/app.rs
=> fix: update desktop file to just launch app library

Cargo.lock, Cargo.toml, src/app.rs, src/widgets/application.rs, src/widgets/group.rs
This seems to be working well after the update.
=> chore: update libcosmic

Cargo.lock, src/app.rs, src/app_group.rs
=> fix: better handling of ongoing dnd when hiding

src/app.rs, src/widgets/application.rs
=> fix: pass press handler to the intern app button

Cargo.lock, Cargo.toml
default feature just enables the clipboard so it should be fine to enable.
=> fix: enable clipboard

Cargo.lock, src/app.rs
=> fix: don't force pop icon theme

src/app.rs, src/app_group.rs, src/widgets/group.rs
fixes https://github.com/pop-os/cosmic-applibrary/issues/77
=> fix: allow DnD back to the home group

Cargo.toml, src/app.rs
fixes #117 and enables the portal feature
=> Fix extra divider

i18n/pl/cosmic_app_library.ftl
Added pin-to-app-tray translation
=> Update cosmic_app_library.ftl PL translation

i18n/en/cosmic_app_library.ftl, src/app.rs
Add group was bare text, add translatable string
See https://github.com/pop-os/cosmic-applibrary/pull/146#issuecomment-2261254828
=> Fix untranslatable string "Add group"

i18n/sk/cosmic_app_library.ftl
=> i18n(sk): Update translation

Cargo.lock, src/app.rs, src/widgets/application.rs, src/widgets/group.rs
This prevents text being missing when Spacious density is used.
=> Make group button height dynamic

src/app.rs
=> fix: do not create new dialog when one already exists.

Cargo.lock, Cargo.toml, rust-toolchain.toml, src/app.rs
requires https://github.com/pop-os/libcosmic/pull/821. Fixes https://github.com/pop-os/cosmic-applibrary/issues/151
=> fix: parse language and region from langtag

src/app.rs
=> feat: avoid overlap

Cargo.lock, src/app.rs, src/widgets/application.rs
=> feat: start app on submit and implement better keyboard navigation

i18n/nl/cosmic_app_library.ftl
https://www.iculture.nl/gids/appbibliotheek/
=> i18n(nl) Changed translation "Applibrary" to "Appbibliotheek"
